# Generated by Django 6.0.6 on 2026-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barbershop_user_alter_barbershop_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('barber_shop', 'date', 'time'), name='unique_active_appointment_per_slot'),
        ),
    ]
