# Generated by Django 6.0.6 on 2026-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_unique_active_appointment_per_slot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barber_shop', 'date', 'time'], name='appt_shop_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barber_shop', 'status'], name='appt_shop_status_idx'),
        ),
    ]
