# Generated by Django 6.0.6 on 2026-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_barbershop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
